// Users
export const GET_USERS = "GET_USERS";
export const USERS_FETCHING = "USERS_FETCHING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Countries
export const GET_COUNTRIES = "GET_COUNTRIES";
export const ADD_COUNTRY = "ADD_COUNTRY";
export const MODIFY_COUNTRY = "MODIFY_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const COUNTRIES_FETCHING = "COUNTRIES_FETCHING";

// Universities
export const GET_UNIVERSITIES = "GET_UNIVERSITIES";
export const ADD_UNIVERSITY = "ADD_UNIVERSITY";
export const MODIFY_UNIVERSITY = "MODIFY_UNIVERSITY";
export const DELETE_UNIVERSITY = "DELETE_UNIVERSITY";
export const UNIVERSITIES_FETCHING = "UNIVERSITIES_FETCHING";

// Errors
export const GET_ERRORS = "GET_ERRORS";
